### ISSUE TITLE
Thank you for sharing.

### ISSUE THREAD

**Issue by LarryEitel** [Yu0614/fastapi-ToDoApp#9]
This was just what I was looking for! Thank you also for sharing your ToDo front-end. Awesome work!

**Comment by Yu0614** [comment]
@LarryEitel 

Hi Larry! 
Firstly, thank you for your message , I'm so glad 😄 
If you have any free time, plz push favorite button to this repo and front-end ! 

P.S

Both of backend  and frontend of this app is not support i18n, maybe you have to translate the comment
written in Japanese, watch out. 


Sincerely.
